import React from 'react';
import { Link } from 'react-router-dom';
import { Calculator, ArrowLeft, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import '../styles/CalculatorLayout.css';

const CalculatorLayout = ({ children, title, description, keywords }) => {
  const handleDownloadPDF = () => {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    
    // Title
    pdf.setFontSize(20);
    pdf.setTextColor(34, 211, 238);
    pdf.text('Calcify', pageWidth / 2, 20, { align: 'center' });
    
    // Calculator name
    pdf.setFontSize(16);
    pdf.setTextColor(0, 0, 0);
    pdf.text(title, pageWidth / 2, 35, { align: 'center' });
    
    // Result section
    pdf.setFontSize(12);
    pdf.setTextColor(50, 50, 50);
    
    const resultElement = document.querySelector('.result-box');
    if (resultElement) {
      const resultText = resultElement.innerText;
      const lines = pdf.splitTextToSize(resultText, pageWidth - 40);
      pdf.text(lines, 20, 50);
    } else {
      pdf.text('No results to display. Please calculate first.', 20, 50);
    }
    
    // Footer
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text('Generated by Calcify - calcify.com', pageWidth / 2, 280, { align: 'center' });
    pdf.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 285, { align: 'center' });
    
    pdf.save(`${title.toLowerCase().replace(/\s+/g, '-')}-result.pdf`);
  };

  return (
    <div className="calculator-page">
      <nav className="navbar glass-effect">
        <div className="nav-container">
          <Link to="/" className="logo">
            <Calculator className="logo-icon" />
            <span className="gradient-text logo-text">Calcify</span>
          </Link>
          <Link to="/" className="back-btn">
            <ArrowLeft size={18} />
            <span>All Calculators</span>
          </Link>
        </div>
      </nav>

      <div className="ad-placeholder" style={{margin: '20px auto', maxWidth: '728px', padding: '0 24px'}}>
        Advertisement Space - Top Banner
      </div>

      <main className="calculator-content">
        <div className="calculator-container">
          <div className="calculator-main">
            <div className="calculator-header">
              <h1 className="calculator-title gradient-text">{title}</h1>
              <p className="calculator-description">{description}</p>
            </div>

            <div className="calculator-box glass-effect">
              {children}
            </div>

            <button onClick={handleDownloadPDF} className="download-btn btn-gradient">
              <Download size={18} />
              Download Result as PDF
            </button>
          </div>

          <aside className="calculator-sidebar">
            <div className="ad-placeholder">
              Advertisement Space<br/>Sidebar Ad
            </div>
          </aside>
        </div>

        <div className="ad-placeholder" style={{margin: '40px auto', maxWidth: '728px'}}>
          Advertisement Space - Bottom Banner
        </div>
      </main>

      <footer className="footer">
        <div className="footer-container">
          <div className="footer-content">
            <div className="footer-logo">
              <Calculator className="logo-icon" />
              <span className="gradient-text">Calcify</span>
            </div>
            <p className="footer-text">
              Your trusted source for online calculators. Fast, accurate, and always free.
            </p>
          </div>
          <div className="footer-bottom">
            <p>© 2025 Calcify. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default CalculatorLayout;
